[project]
name = "sorting-visualizer"
version = "0.1.0"
description = "script to vuisualize sorting algorithms"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "matplotlib>=3.10.3",
    "numpy>=2.2.6",
]
